/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: client_server.proto */

#ifndef PROTOBUF_C_client_5fserver_2eproto__INCLUDED
#define PROTOBUF_C_client_5fserver_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ClientServer__Login ClientServer__Login;
typedef struct _ClientServer__LoginResult ClientServer__LoginResult;

/* --- enums --- */

typedef enum _ClientServer__ResultCode {
  CLIENT_SERVER__RESULT_CODE__LOGIN_FAILURE = 1,
  CLIENT_SERVER__RESULT_CODE__LOGIN_SUCCESS = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLIENT_SERVER__RESULT_CODE)
} ClientServer__ResultCode;

/* --- messages --- */

struct  _ClientServer__Login
{
  ProtobufCMessage base;
  char *name;
  char *password;
  protobuf_c_boolean has_login_result;
  ClientServer__ResultCode login_result;
};
#define CLIENT_SERVER__LOGIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_server__login__descriptor) \
    , NULL, NULL, 0,0 }


struct  _ClientServer__LoginResult
{
  ProtobufCMessage base;
  ClientServer__ResultCode login_result;
  char *own_session_id;
};
#define CLIENT_SERVER__LOGIN_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_server__login_result__descriptor) \
    , 0, NULL }



/* ClientServer__Login methods */
void   client_server__login__init
                     (ClientServer__Login         *message);
size_t client_server__login__get_packed_size
                     (const ClientServer__Login   *message);
size_t client_server__login__pack
                     (const ClientServer__Login   *message,
                      uint8_t             *out);
size_t client_server__login__pack_to_buffer
                     (const ClientServer__Login   *message,
                      ProtobufCBuffer     *buffer);
ClientServer__Login *
       client_server__login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_server__login__free_unpacked
                     (ClientServer__Login *message,
                      ProtobufCAllocator *allocator);
/* ClientServer__LoginResult methods */
void   client_server__login_result__init
                     (ClientServer__LoginResult         *message);
size_t client_server__login_result__get_packed_size
                     (const ClientServer__LoginResult   *message);
size_t client_server__login_result__pack
                     (const ClientServer__LoginResult   *message,
                      uint8_t             *out);
size_t client_server__login_result__pack_to_buffer
                     (const ClientServer__LoginResult   *message,
                      ProtobufCBuffer     *buffer);
ClientServer__LoginResult *
       client_server__login_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_server__login_result__free_unpacked
                     (ClientServer__LoginResult *message,
                      ProtobufCAllocator *allocator);

/* --- per-message closures --- */

typedef void (*ClientServer__Login_Closure)
                 (const ClientServer__Login *message,
                  void *closure_data);
typedef void (*ClientServer__LoginResult_Closure)
                 (const ClientServer__LoginResult *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    client_server__result_code__descriptor;
extern const ProtobufCMessageDescriptor client_server__login__descriptor;
extern const ProtobufCMessageDescriptor client_server__login_result__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_client_5fserver_2eproto__INCLUDED */
