/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: client_server.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "client_server.pb-c.h"
void   client_server__login__init
                     (ClientServer__Login         *message)
{
  static ClientServer__Login init_value = CLIENT_SERVER__LOGIN__INIT;
  *message = init_value;
}
size_t client_server__login__get_packed_size
                     (const ClientServer__Login *message)
{
  assert(message->base.descriptor == &client_server__login__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_server__login__pack
                     (const ClientServer__Login *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_server__login__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_server__login__pack_to_buffer
                     (const ClientServer__Login *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_server__login__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientServer__Login *
       client_server__login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientServer__Login *)
     protobuf_c_message_unpack (&client_server__login__descriptor,
                                allocator, len, data);
}
void   client_server__login__free_unpacked
                     (ClientServer__Login *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &client_server__login__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_server__login_result__init
                     (ClientServer__LoginResult         *message)
{
  static ClientServer__LoginResult init_value = CLIENT_SERVER__LOGIN_RESULT__INIT;
  *message = init_value;
}
size_t client_server__login_result__get_packed_size
                     (const ClientServer__LoginResult *message)
{
  assert(message->base.descriptor == &client_server__login_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_server__login_result__pack
                     (const ClientServer__LoginResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_server__login_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_server__login_result__pack_to_buffer
                     (const ClientServer__LoginResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_server__login_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientServer__LoginResult *
       client_server__login_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientServer__LoginResult *)
     protobuf_c_message_unpack (&client_server__login_result__descriptor,
                                allocator, len, data);
}
void   client_server__login_result__free_unpacked
                     (ClientServer__LoginResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &client_server__login_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client_server__login__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientServer__Login, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientServer__Login, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "login_result",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ClientServer__Login, has_login_result),
    offsetof(ClientServer__Login, login_result),
    &client_server__result_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_server__login__field_indices_by_name[] = {
  2,   /* field[2] = login_result */
  0,   /* field[0] = name */
  1,   /* field[1] = password */
};
static const ProtobufCIntRange client_server__login__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor client_server__login__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_server.Login",
  "Login",
  "ClientServer__Login",
  "client_server",
  sizeof(ClientServer__Login),
  3,
  client_server__login__field_descriptors,
  client_server__login__field_indices_by_name,
  1,  client_server__login__number_ranges,
  (ProtobufCMessageInit) client_server__login__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_server__login_result__field_descriptors[2] =
{
  {
    "login_result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientServer__LoginResult, login_result),
    &client_server__result_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "own_session_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientServer__LoginResult, own_session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_server__login_result__field_indices_by_name[] = {
  0,   /* field[0] = login_result */
  1,   /* field[1] = own_session_id */
};
static const ProtobufCIntRange client_server__login_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor client_server__login_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_server.LoginResult",
  "LoginResult",
  "ClientServer__LoginResult",
  "client_server",
  sizeof(ClientServer__LoginResult),
  2,
  client_server__login_result__field_descriptors,
  client_server__login_result__field_indices_by_name,
  1,  client_server__login_result__number_ranges,
  (ProtobufCMessageInit) client_server__login_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue client_server__result_code__enum_values_by_number[2] =
{
  { "LOGIN_FAILURE", "CLIENT_SERVER__RESULT_CODE__LOGIN_FAILURE", 1 },
  { "LOGIN_SUCCESS", "CLIENT_SERVER__RESULT_CODE__LOGIN_SUCCESS", 2 },
};
static const ProtobufCIntRange client_server__result_code__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex client_server__result_code__enum_values_by_name[2] =
{
  { "LOGIN_FAILURE", 0 },
  { "LOGIN_SUCCESS", 1 },
};
const ProtobufCEnumDescriptor client_server__result_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "client_server.ResultCode",
  "ResultCode",
  "ClientServer__ResultCode",
  "client_server",
  2,
  client_server__result_code__enum_values_by_number,
  2,
  client_server__result_code__enum_values_by_name,
  1,
  client_server__result_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
