/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: remote_log.proto */

#ifndef PROTOBUF_C_remote_5flog_2eproto__INCLUDED
#define PROTOBUF_C_remote_5flog_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _RemoteLog__Log RemoteLog__Log;


/* --- enums --- */


/* --- messages --- */

struct  _RemoteLog__Log
{
  ProtobufCMessage base;
  uint64_t time;
  char *log;
};
#define REMOTE_LOG__LOG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&remote_log__log__descriptor) \
    , 0, NULL }


/* RemoteLog__Log methods */
void   remote_log__log__init
                     (RemoteLog__Log         *message);
size_t remote_log__log__get_packed_size
                     (const RemoteLog__Log   *message);
size_t remote_log__log__pack
                     (const RemoteLog__Log   *message,
                      uint8_t             *out);
size_t remote_log__log__pack_to_buffer
                     (const RemoteLog__Log   *message,
                      ProtobufCBuffer     *buffer);
RemoteLog__Log *
       remote_log__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   remote_log__log__free_unpacked
                     (RemoteLog__Log *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RemoteLog__Log_Closure)
                 (const RemoteLog__Log *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor remote_log__log__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_remote_5flog_2eproto__INCLUDED */
