/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: remote_log.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "remote_log.pb-c.h"
void   remote_log__log__init
                     (RemoteLog__Log         *message)
{
  static RemoteLog__Log init_value = REMOTE_LOG__LOG__INIT;
  *message = init_value;
}
size_t remote_log__log__get_packed_size
                     (const RemoteLog__Log *message)
{
  assert(message->base.descriptor == &remote_log__log__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remote_log__log__pack
                     (const RemoteLog__Log *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remote_log__log__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remote_log__log__pack_to_buffer
                     (const RemoteLog__Log *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remote_log__log__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RemoteLog__Log *
       remote_log__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RemoteLog__Log *)
     protobuf_c_message_unpack (&remote_log__log__descriptor,
                                allocator, len, data);
}
void   remote_log__log__free_unpacked
                     (RemoteLog__Log *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &remote_log__log__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor remote_log__log__field_descriptors[2] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RemoteLog__Log, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RemoteLog__Log, log),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remote_log__log__field_indices_by_name[] = {
  1,   /* field[1] = log */
  0,   /* field[0] = time */
};
static const ProtobufCIntRange remote_log__log__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor remote_log__log__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "remote_log.log",
  "Log",
  "RemoteLog__Log",
  "remote_log",
  sizeof(RemoteLog__Log),
  2,
  remote_log__log__field_descriptors,
  remote_log__log__field_indices_by_name,
  1,  remote_log__log__number_ranges,
  (ProtobufCMessageInit) remote_log__log__init,
  NULL,NULL,NULL    /* reserved[123] */
};
